# Schema for the configuration files of the simplesamlphpcustom module.
equipment.settings:
  type: config_object
  label: 'equipment settings'
  mapping:
    equipment_form_id:
      type: string
      label: 'Equipment Form Id'
    equipment_view_id:
      type: string
      label: 'Equipment View Id'
